### ISSUE TITLE
Пример: Padawans возвращает ошибку при выполнении задачи Task 6

### ISSUE THREAD

**Issue by alexander-rykov** [EPM-RD-NETLAB/padawans-issues#1]
**Проверка**
Да, код собирается без ошибок, unit tests отрабатывают корректно.

**Опишите ошибку**
1. Код залит в репозиторий (ссылка).
2. В padawans выбрана задача Task 6 и указанный репозиторий.
3. Запускаю задачу на выполнение.
4. Счетчик попыток показывает 2, предыдущее значение 1. Padawans сообщает, что возникла ошибка во время сборки.

**Дата/время**
18.02.2019 17:06 MSQ

**Текст ошибки (если есть)**
(Текст ошибки)

**Скриншоты**
(Ссылка на скриншот)

**Comment by EPM-RD-NETLAB** [comment]
Ошибка принята, изучаем.

**Comment by EPM-RD-NETLAB** [comment]
Ошибка исправлена, попробуйте еще раз.
