### ISSUE TITLE
Padawans не возвращает никаких ошибок и выдаёт 100% прохождение тестов

### ISSUE THREAD

**Issue by ProXAlex** [EPM-RD-NETLAB/padawans-issues#2]
> **Проверка**
> Проверьте, собирается ли код Вашей задачи локально без ошибок, выполняются ли без ошибок unit tests.

Код собирается без ошибок, локальные unit tests отрабатывают корректно. Загружаю на падаванс, если требуется исправляю код по итогам hidden тестов. Получаю 100% по всем заданиям. 

> **Дата/время**
> Оставьте дату и время возникновения ошибки.

Не смог поймать ошибку, поэтому время указать не могу.

> **Текст ошибки (если есть)**
> Скопируйте текст ошибки, которую Вам выдал браузер.

Текст ошибки не увидел, но все в чате пишут что тесты написаны неправильно, и что падаванс не умеет компилить проекты. Их(людей, которые пишут про ошибки) слишком много, и они супер профи(зачем тогда пошли на тренинг?), чтобы они могли написать или сделать что-то неверно, поэтому я считаю что делаю что-то не так.

Уважаемые разработчики, пожалуйста исправьте данный баг =), а то я не могу запилить bug report со скринами и текстами ошибок. Спасибо!

**Comment by EPM-RD-NETLAB** [comment]
К сожалению, исправить правильное поведение мы не можем.
