### ISSUE TITLE
Padawans возвращает ошибку при выполнении задачи 8

### ISSUE THREAD

**Issue by AlexeiBucha** [EPM-RD-NETLAB/padawans-issues#3]
**Проверка**
Код собирается, и тесты все выполнялись.

**Опишите ошибку**
Ошибка повторилась 2 раза подряд. Первый раз, примерно за 20 минут до указанного ниже времени.  Attempts стало 1. Перед второй попыткой скачал и залил все по новой. Код не  менял. После второго сабмита ошибка осталась прежней.  Attempts осталось 1.  Вечером полностью переписал код и ошибок больше не было.  

https://github.com/AlexeiBucha/PadawansTask8/commit/c08a76fd88895015e762188a9a8cff37f3e73625

**Дата/время**
11.18  17.02.19

**Текст ошибки (если есть)**
Something went wrong during building. Please try again.

**Скриншоты**
https://imgur.com/a/7thWV0k

**Дополнительная информация**
.

**Comment by EPM-RD-NETLAB** [comment]
Сообщение "Something went wrong during building" означает, что произошла ошибка во время сборки кода. Проверьте, действительно ли вы поместили ваш локальный код в гитхаб.
